import type { CategoryId, Language } from './types'

export const languageNames: Record<Language, string> = {
  en: 'English',
  fr: 'Français',
  ar: 'العربية',
  tn: 'Tounsi',
}

export const categoryIds: CategoryId[] = [
  'documents',
  'keys',
  'phones',
  'wallets',
  'bags',
  'pets',
  'other',
]

type Dictionary = Record<string, string>

export const translations: Record<Language, Dictionary> = {
  en: {
    tagline: 'Lost, found, reunited.',
    browse: 'Browse items',
    how: 'How it works',
    postFound: 'I found something',
    postLost: 'I lost something',
    heroEyebrow: 'Made for Tunisia, powered by neighbours',
    heroTitleA: 'Lost it?',
    heroTitleB: "Let's bring it home.",
    heroText: 'Search what people found near you, or share an item in under a minute. Free, simple and safe.',
    searchPlaceholder: 'Search a name, item or place…',
    allTunisia: 'All Tunisia',
    search: 'Search',
    example: 'Try “Amina”, “keys” or “Sousse”',
    reunited: 'items reunited',
    categories: 'Browse by category',
    categoriesText: 'From important documents to everyday things.',
    latest: 'Recently posted',
    latestText: 'A few things your neighbours are looking after.',
    findEyebrow: 'Search real community posts',
    findTitle: 'Find what you lost.',
    findText: 'If it is a document, type the name written on it. For anything else, search the item, colour, place or another detail.',
    searchHelp: 'Search by name, item, location or description',
    results: 'results',
    noPosts: 'No items have been posted yet.',
    noPostsText: 'This space will show real community posts only. Be the first to post something you found or lost.',
    firstPost: 'Create the first post',
    viewAll: 'View all',
    all: 'All',
    found: 'Found',
    lost: 'Lost',
    documents: 'Documents',
    keys: 'Keys',
    phones: 'Phones',
    wallets: 'Wallets',
    bags: 'Bags',
    pets: 'Pets',
    other: 'Other',
    foundOn: 'Found',
    lostOn: 'Lost',
    returned: 'Returned',
    openItem: 'View details',
    noResults: 'Nothing matches that search yet.',
    noResultsText: 'Try another word or post what you lost so the community can help.',
    clearSearch: 'Clear search',
    stepOne: 'Share it',
    stepOneText: 'Add a photo, a simple description and the approximate place.',
    stepTwo: 'Get matched',
    stepTwoText: 'People can search by name, object, category or location.',
    stepThree: 'Return safely',
    stepThreeText: 'Verify the real owner privately, then arrange a safe handover.',
    safetyTitle: 'Private by design.',
    safetyText: 'For IDs and documents, only show the name and photo. Numbers, addresses, signatures and codes must stay hidden.',
    ctaTitle: 'Found something?',
    ctaText: 'One small post could make someone’s whole day.',
    footerText: 'A community project helping Tunisia look after its things—and each other.',
    createPost: 'Create a post',
    editLater: 'You can update or close it later.',
    whatHappened: 'What happened?',
    itemCategory: 'Category',
    addPhoto: 'Add a photo',
    photoHint: 'JPG or PNG, up to 6 MB',
    choosePhoto: 'Choose photo',
    changePhoto: 'Change photo',
    documentSafety: 'Protect private information',
    documentSafetyText: 'Before uploading, crop or cover all ID numbers, addresses, signatures, QR codes and barcodes. Show only the photo and name.',
    confirmPrivacy: 'I confirm all private details are hidden',
    scanName: 'Read name from photo',
    scanning: 'Reading photo…',
    scanHint: 'Runs in your browser. Always check the result.',
    nameOnItem: 'Name on the item',
    namePlaceholder: 'e.g. Amina Ben Salem',
    nameHelp: 'The full name helps search, but only the first name and last initial appear publicly.',
    itemTitle: 'Item title',
    titlePlaceholder: 'e.g. National identity card',
    description: 'Short description',
    descriptionPlaceholder: 'Add a useful detail without revealing how to prove ownership…',
    where: 'Where?',
    locationPlaceholder: 'e.g. Lafayette, Tunis',
    when: 'When?',
    publish: 'Publish post',
    optional: 'optional',
    contactHeading: 'How should people contact you?',
    contactHelp: 'These contacts will appear on the item post so the owner or finder can reach you. All fields are optional.',
    phone: 'Phone number',
    facebook: 'Facebook profile or username',
    instagram: 'Instagram username',
    untitledFound: 'Found item',
    untitledLost: 'Lost item',
    notProvided: 'Not provided',
    foundThis: 'I found this item',
    contactPoster: 'Contact the person who posted this',
    contactFinder: 'Contact the person who found this',
    cancel: 'Cancel',
    required: 'Please complete the required fields.',
    photoTooLarge: 'That photo is larger than 6 MB.',
    privacyRequired: 'Please confirm that private document details are hidden.',
    postPublished: 'Your post is now live.',
    ocrFailed: 'We could not read a clear name. You can enter it manually.',
    claimThis: 'This might be mine',
    claimTitle: 'Claim this item',
    claimText: 'Describe one private detail only the real owner would know. It will be shared privately with the finder.',
    proofPlaceholder: 'A hidden detail, what is inside, lock-screen image…',
    yourContact: 'Your phone or email',
    sendClaim: 'Send private claim',
    claimSent: 'Your claim was sent privately.',
    location: 'Location',
    date: 'Date',
    close: 'Close',
    safeReminder: 'Meet in a public place and never pay to recover an item.',
  },
  fr: {
    tagline: 'Perdu, trouvé, retrouvé.', browse: 'Voir les objets', how: 'Comment ça marche', postFound: "J’ai trouvé", postLost: "J’ai perdu",
    heroEyebrow: 'Créé pour la Tunisie, porté par les voisins', heroTitleA: 'Un objet perdu ?', heroTitleB: 'Ramenons-le à la maison.',
    heroText: 'Recherchez les objets trouvés près de chez vous ou publiez-en un en moins d’une minute. Gratuit, simple et sûr.',
    searchPlaceholder: 'Rechercher un nom, objet ou lieu…', allTunisia: 'Toute la Tunisie', search: 'Rechercher', example: 'Essayez « Amina », « clés » ou « Sousse »',
    reunited: 'objets rendus', categories: 'Explorer par catégorie', categoriesText: 'Des documents importants aux objets du quotidien.', latest: 'Publications récentes',
    latestText: 'Les objets réellement publiés par la communauté.', findEyebrow: 'Rechercher dans les publications réelles', findTitle: 'Retrouvez ce que vous avez perdu.', findText: 'Pour un document, saisissez le nom inscrit dessus. Sinon, recherchez l’objet, sa couleur, le lieu ou un autre détail.', searchHelp: 'Nom, objet, lieu ou description', results: 'résultats', noPosts: 'Aucun objet publié pour le moment.', noPostsText: 'Seules les vraies publications apparaîtront ici. Soyez la première personne à publier un objet trouvé ou perdu.', firstPost: 'Créer la première publication', viewAll: 'Tout voir', all: 'Tous', found: 'Trouvé', lost: 'Perdu', documents: 'Documents', keys: 'Clés', phones: 'Téléphones', wallets: 'Portefeuilles', bags: 'Sacs', pets: 'Animaux', other: 'Autre',
    foundOn: 'Trouvé', lostOn: 'Perdu', returned: 'Rendu', openItem: 'Voir les détails', noResults: 'Aucun résultat pour cette recherche.', noResultsText: 'Essayez un autre mot ou publiez ce que vous avez perdu.', clearSearch: 'Effacer la recherche',
    stepOne: 'Publiez', stepOneText: 'Ajoutez une photo, une description simple et le lieu approximatif.', stepTwo: 'Trouvez une correspondance', stepTwoText: 'Recherche par nom, objet, catégorie ou lieu.', stepThree: 'Rendez en sécurité', stepThreeText: 'Vérifiez le propriétaire en privé, puis organisez la remise.',
    safetyTitle: 'La confidentialité avant tout.', safetyText: 'Pour les pièces d’identité, montrez uniquement le nom et la photo. Masquez numéros, adresses, signatures et codes.',
    ctaTitle: 'Vous avez trouvé quelque chose ?', ctaText: 'Une petite publication peut sauver la journée de quelqu’un.', footerText: 'Un projet communautaire pour prendre soin de nos affaires—et des autres.',
    createPost: 'Créer une publication', editLater: 'Vous pourrez la modifier ou la fermer plus tard.', whatHappened: 'Que s’est-il passé ?', itemCategory: 'Catégorie', addPhoto: 'Ajouter une photo', photoHint: 'JPG ou PNG, 6 Mo maximum', choosePhoto: 'Choisir une photo', changePhoto: 'Changer la photo',
    documentSafety: 'Protégez les informations privées', documentSafetyText: 'Avant de publier, masquez les numéros, adresses, signatures, QR codes et codes-barres. Montrez uniquement la photo et le nom.', confirmPrivacy: 'Je confirme que les informations privées sont masquées', scanName: 'Lire le nom sur la photo', scanning: 'Lecture de la photo…', scanHint: 'Effectué dans votre navigateur. Vérifiez toujours le résultat.',
    nameOnItem: 'Nom sur l’objet', namePlaceholder: 'ex. Amina Ben Salem', nameHelp: 'Le nom complet facilite la recherche, mais seul le prénom et l’initiale seront publics.', itemTitle: 'Titre', titlePlaceholder: 'ex. Carte d’identité nationale', description: 'Courte description', descriptionPlaceholder: 'Ajoutez un détail utile sans révéler la preuve de propriété…', where: 'Où ?', locationPlaceholder: 'ex. Lafayette, Tunis', when: 'Quand ?', publish: 'Publier', optional: 'facultatif', contactHeading: 'Comment souhaitez-vous être contacté ?', contactHelp: 'Ces contacts apparaîtront sur la publication pour que le propriétaire ou la personne qui trouve l’objet puisse vous joindre. Tout est facultatif.', phone: 'Numéro de téléphone', facebook: 'Profil ou identifiant Facebook', instagram: 'Identifiant Instagram', untitledFound: 'Objet trouvé', untitledLost: 'Objet perdu', notProvided: 'Non renseigné', foundThis: 'J’ai trouvé cet objet', contactPoster: 'Contacter la personne', contactFinder: 'Contacter la personne qui l’a trouvé', cancel: 'Annuler', required: 'Veuillez remplir les champs obligatoires.', photoTooLarge: 'Cette photo dépasse 6 Mo.', privacyRequired: 'Confirmez que les informations privées sont masquées.', postPublished: 'Votre publication est en ligne.', ocrFailed: 'Impossible de lire clairement le nom. Vous pouvez le saisir.',
    claimThis: 'C’est peut-être à moi', claimTitle: 'Réclamer cet objet', claimText: 'Décrivez un détail privé que seul le propriétaire connaît.', proofPlaceholder: 'Un détail caché, le contenu, l’écran de verrouillage…', yourContact: 'Votre téléphone ou e-mail', sendClaim: 'Envoyer la demande privée', claimSent: 'Votre demande a été envoyée.', location: 'Lieu', date: 'Date', close: 'Fermer', safeReminder: 'Rencontrez-vous dans un lieu public et ne payez jamais pour récupérer un objet.',
  },
  ar: {
    tagline: 'ضائع، موجود، عاد لصاحبه.', browse: 'تصفّح الأغراض', how: 'كيف تعمل', postFound: 'وجدت شيئًا', postLost: 'أضعت شيئًا',
    heroEyebrow: 'صُنع لتونس، بروح التعاون بين الناس', heroTitleA: 'ضاع منك شيء؟', heroTitleB: 'خلّينا نرجّعوه.', heroText: 'ابحث عمّا وجده الناس بالقرب منك، أو انشر غرضًا في أقل من دقيقة. مجانًا وببساطة وأمان.',
    searchPlaceholder: 'ابحث باسم أو غرض أو مكان…', allTunisia: 'كل تونس', search: 'بحث', example: 'جرّب «أمينة» أو «مفاتيح» أو «سوسة»', reunited: 'غرض عاد لصاحبه',
    categories: 'تصفّح حسب النوع', categoriesText: 'من الوثائق المهمة إلى الأغراض اليومية.', latest: 'أحدث المنشورات', latestText: 'منشورات حقيقية من المجتمع.', findEyebrow: 'ابحث في منشورات المجتمع الحقيقية', findTitle: 'اعثر على ما أضعته.', findText: 'إذا كانت وثيقة، اكتب الاسم الموجود عليها. ولأي غرض آخر، ابحث عن اسمه أو لونه أو مكانه أو أي تفصيل.', searchHelp: 'ابحث بالاسم أو الغرض أو المكان أو الوصف', results: 'نتيجة', noPosts: 'لا توجد منشورات بعد.', noPostsText: 'ستظهر هنا منشورات حقيقية فقط. كن أول من ينشر غرضًا وجده أو أضاعه.', firstPost: 'أنشئ أول منشور', viewAll: 'عرض الكل', all: 'الكل', found: 'موجود', lost: 'ضائع', documents: 'وثائق', keys: 'مفاتيح', phones: 'هواتف', wallets: 'محافظ', bags: 'حقائب', pets: 'حيوانات', other: 'أخرى', foundOn: 'وُجد', lostOn: 'ضاع', returned: 'عاد لصاحبه', openItem: 'عرض التفاصيل', noResults: 'لا توجد نتائج مطابقة.', noResultsText: 'جرّب كلمة أخرى أو انشر ما أضعته.', clearSearch: 'مسح البحث',
    stepOne: 'انشره', stepOneText: 'أضف صورة ووصفًا بسيطًا والمكان التقريبي.', stepTwo: 'اعثر عليه', stepTwoText: 'يمكن البحث بالاسم أو الغرض أو النوع أو المكان.', stepThree: 'أعِده بأمان', stepThreeText: 'تحقق من المالك الحقيقي بشكل خاص ثم رتّبا التسليم.',
    safetyTitle: 'الخصوصية أولًا.', safetyText: 'في بطاقات الهوية والوثائق، أظهر الاسم والصورة فقط. يجب إخفاء الأرقام والعناوين والتوقيعات والرموز.', ctaTitle: 'وجدت شيئًا؟', ctaText: 'منشور صغير قد يصنع يوم شخص كاملًا.', footerText: 'مشروع مجتمعي يساعد تونس على حماية أغراضنا—وبعضنا البعض.',
    createPost: 'إنشاء منشور', editLater: 'يمكنك تعديله أو إغلاقه لاحقًا.', whatHappened: 'ماذا حدث؟', itemCategory: 'النوع', addPhoto: 'أضف صورة', photoHint: 'JPG أو PNG، حتى 6 ميغابايت', choosePhoto: 'اختر صورة', changePhoto: 'غيّر الصورة', documentSafety: 'احمِ المعلومات الخاصة', documentSafetyText: 'قبل الرفع، اخفِ كل الأرقام والعناوين والتوقيعات ورموز QR والباركود. أظهر الصورة والاسم فقط.', confirmPrivacy: 'أؤكد أن كل المعلومات الخاصة مخفية', scanName: 'قراءة الاسم من الصورة', scanning: 'جارٍ قراءة الصورة…', scanHint: 'تتم القراءة داخل متصفحك. تحقق دائمًا من النتيجة.', nameOnItem: 'الاسم على الغرض', namePlaceholder: 'مثال: أمينة بن سالم', nameHelp: 'الاسم الكامل يساعد في البحث، لكن الاسم الأول والحرف الأول فقط يظهران للعموم.', itemTitle: 'عنوان الغرض', titlePlaceholder: 'مثال: بطاقة تعريف وطنية', description: 'وصف قصير', descriptionPlaceholder: 'أضف معلومة مفيدة دون كشف دليل الملكية…', where: 'أين؟', locationPlaceholder: 'مثال: لافايات، تونس', when: 'متى؟', publish: 'انشر', optional: 'اختياري', contactHeading: 'كيف تفضل أن يتواصل الناس معك؟', contactHelp: 'ستظهر وسائل التواصل في المنشور حتى يتواصل معك مالك الغرض أو من وجده. كل الخانات اختيارية.', phone: 'رقم الهاتف', facebook: 'حساب فيسبوك', instagram: 'حساب إنستغرام', untitledFound: 'غرض موجود', untitledLost: 'غرض ضائع', notProvided: 'غير محدد', foundThis: 'وجدت هذا الغرض', contactPoster: 'تواصل مع صاحب المنشور', contactFinder: 'تواصل مع الشخص الذي وجد الغرض', cancel: 'إلغاء', required: 'يرجى إكمال الخانات المطلوبة.', photoTooLarge: 'حجم الصورة أكبر من 6 ميغابايت.', privacyRequired: 'أكد أن معلومات الوثيقة الخاصة مخفية.', postPublished: 'تم نشر إعلانك.', ocrFailed: 'لم نتمكن من قراءة اسم واضح. يمكنك كتابته يدويًا.', claimThis: 'قد يكون لي', claimTitle: 'اطلب استرجاع الغرض', claimText: 'اكتب معلومة خاصة لا يعرفها إلا المالك الحقيقي.', proofPlaceholder: 'تفصيل مخفي، ما بداخل الغرض، صورة شاشة القفل…', yourContact: 'هاتفك أو بريدك', sendClaim: 'أرسل الطلب بشكل خاص', claimSent: 'تم إرسال طلبك بشكل خاص.', location: 'المكان', date: 'التاريخ', close: 'إغلاق', safeReminder: 'تقابلوا في مكان عام ولا تدفع أبدًا لاسترجاع غرض.',
  },
  tn: {
    tagline: 'Dhaa3, l9ineh, rja3.', browse: 'Chouf el 7ajet', how: 'Kifeh tekhdem', postFound: 'L9it 7aja', postLost: 'Dha3etli 7aja',
    heroEyebrow: 'Ma3moula l Tounes, b t3awen ennes', heroTitleA: 'Dha3etlek 7aja?', heroTitleB: 'Nraj3ouhelek.', heroText: 'Lawwej fel 7ajet elli l9awhom ennes 9riblek, walla habbet annonce fi a9al men d9i9a. Blech, sehla w amna.',
    searchPlaceholder: 'Lawwej b esm, 7aja walla blassa…', allTunisia: 'Tounes lkol', search: 'Lawwej', example: 'Jarreb “Amina”, “mfete7” walla “Sousse”', reunited: '7aja raj3et', categories: 'Lawwej bel catégorie', categoriesText: 'Mel awra9 el mohema lel 7ajet el kol.', latest: 'Elli t7attou jدد', latestText: 'Annonces s7a7 mel communauté.', findEyebrow: 'Lawwej fel annonces es7a7', findTitle: 'L9a elli dha3lek.', findText: 'Ken wara9, ekteb el esm elli 3lihom. W ken 7aja okhra, lawwej bel esm, loun, blassa walla ay détail.', searchHelp: 'Esm, 7aja, blassa walla wasf', results: 'résultats', noPosts: 'Mazal ma fama 7atta annonce.', noPostsText: 'Houni yodh’hrou ken annonces s7a7. Koun awel we7ed yhabbet 7aja l9aha walla dha3etlou.', firstPost: 'Habbet awel annonce', viewAll: 'Chouf el kol', all: 'El kol', found: 'Mal9i', lost: 'Dhaaye3', documents: 'Awra9', keys: 'Mfete7', phones: 'Talifounet', wallets: 'Portefeuilles', bags: 'Sacs', pets: '7ayawenet', other: 'Okhra', foundOn: 'L9inah', lostOn: 'Dhaa3', returned: 'Rja3', openItem: 'Chouf details', noResults: 'Ma l9ina chay ymatchi.', noResultsText: 'Jarreb kelma okhra walla habbet elli dha3lek.', clearSearch: 'Fassa5 el recherche',
    stepOne: 'Habbet annonce', stepOneText: '7ot taswira, wasf sghir w win ta9riban.', stepTwo: 'L9a el match', stepTwoText: 'Ennes tnajem tlawej bel esm, el 7aja, catégorie walla blassa.', stepThree: 'Rajja3ha b aman', stepThreeText: 'Thabet melli howa moulaha w etfehmou fi blassa amna.', safetyTitle: 'El privé yeb9a privé.', safetyText: 'Fel CIN wel awra9, warri ken el esm wel taswira. Ghatti les numéros, l’adresse, signature wel codes.', ctaTitle: 'L9it 7aja?', ctaText: 'Annonce sghira tnajem tfarra7 3abd.', footerText: 'Projet mta3 ennes y3awen Tounes t7afedh 3la 7ajetha—w 3la b3adhna.',
    createPost: 'Habbet annonce', editLater: 'Tnajem tbadelha walla tsakkerha ba3d.', whatHappened: 'Chnowa sar?', itemCategory: 'Catégorie', addPhoto: 'Zid taswira', photoHint: 'JPG walla PNG, max 6 MB', choosePhoto: 'Ekhtar taswira', changePhoto: 'Baddel taswira', documentSafety: 'E7mi el ma3loumet el privé', documentSafetyText: '9bal ma thabbet, ghatti les numéros, l’adresse, signature, QR code wel barcode. Warri ken el taswira wel esm.', confirmPrivacy: 'Net2aked elli el ma3loumet el privé lkol mghattin', scanName: 'E9ra el esm mel taswira', scanning: 'Na9raw fel taswira…', scanHint: 'Tekhdem fi navigateur mte3ek. Thabet mel résultat.', nameOnItem: 'El esm 3al 7aja', namePlaceholder: 'mathalan: Amina Ben Salem', nameHelp: 'El esm kemel y3awen fel recherche, ama lel 3oumoum yodhher ken el prénom w awal 7arf.', itemTitle: 'Chnowa el 7aja?', titlePlaceholder: 'mathalan: Carte d’identité', description: 'Wasf sghir', descriptionPlaceholder: 'Zid détail y3awen, ama ma tkachafech kifeh yetthabet moulaha…', where: 'Win?', locationPlaceholder: 'mathalan: Lafayette, Tunis', when: 'Wa9tech?', publish: 'Habbet', optional: 'ekhtiyari', contactHeading: 'Kifeh t7eb ennes ykalmouk?', contactHelp: 'El contacts yodh’hrou fel annonce bech moul el 7aja walla elli l9aha ynajem ykalmek. El kol ekhtiyari.', phone: 'Noumrou talifoun', facebook: 'Facebook profile walla username', instagram: 'Instagram username', untitledFound: '7aja mal9oua', untitledLost: '7aja dhaay3a', notProvided: 'Mahouch mawjoud', foundThis: 'L9it el 7aja hedhi', contactPoster: 'Kallem moul el annonce', contactFinder: 'Kallem elli l9a el 7aja', cancel: 'Annuler', required: 'Kammel el ma3loumet elli lezem.', photoTooLarge: 'El taswira akber men 6 MB.', privacyRequired: 'Aked elli el ma3loumet el privé mghattin.', postPublished: 'El annonce mte3ek habtet.', ocrFailed: 'Ma 9darnach na9raw esm wadha7. Tnajem tektbou.', claimThis: 'Tnajem tkoun mte3i', claimTitle: 'Otlob el 7aja', claimText: 'Okteb détail privé ma ya3rfou ken moul el 7aja.', proofPlaceholder: 'Détail mekhfi, chnowa feha, taswiret lock screen…', yourContact: 'Talifounek walla email', sendClaim: 'Ab3ath el demande privé', claimSent: 'El demande tba3thet privé.', location: 'El blassa', date: 'Etterikh', close: 'Sakker', safeReminder: 'Et9ablou fi blassa publique w ma tkhalles 7ad bech yrajja3lek 7ajtek.',
  },
}
